import type { Metadata } from "next";
import { Inter, Kanit } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import UiWrapper from "./UiWrapper";

const inter = Inter({ subsets: ["latin"] });
const kanit = Kanit({ weight: "300", subsets: ["thai"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <Toaster />
        <div className="flex w-full">
          <UiWrapper>{children}</UiWrapper>
        </div>
      </body>
    </html>
  );
}
